warning_threshold: 15

disabled_rules:
  - trailing_whitespace
  
opt_in_rules:
  - force_unwrapping

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 500

type_body_length:
  warning: 400
  error: 450

control_statement:
  error
